### PR TITLE
Remove ImageMagick

### PR DESCRIPTION
**Pull request by jahammo2**
Because it's not used in very many rails projects

### CODE REVIEW

**Comment by dkniffin** [comment]
Per the discussion in the tape slack room, I think instead of removing this from tape, we should move it to it's own role, and add that role, commented out, to `omnibox.example.yml`

@jahammo2 Let me know if you need help doing that.

**Comment by BrandonMathis** [comment]
Agreed. Can we move this to a role called 'imagemagick' that is commented out in the `omnibox.example.yml` file?

**Comment by jahammo2** [comment]
Will do fam

**Comment by dkniffin** [comment]
Looks good. One last knitpick: I'd call the role "imagemagick", so it matches up with our other naming (nginx, delayed_job, etc)

**Comment by jahammo2** [comment]
@dkniffin Sorry, I had forgotten about this PR. I'll let you merge though (in case you need anything else to change).

**Comment by dkniffin** [comment]
Looks good. Merging.

**Pull request merged**
