### PR TITLE
Add Travis integration

### PR DESCRIPTION
**Pull request by dkniffin**
Not ready for review yet.

### CODE REVIEW

**Comment by BrandonMathis** [comment]
Is this ready for review?

**Comment by dkniffin** [comment]
@BrandonMathis Nope, not yet. I need admin access to the git repo, so I can add travis integration.

**Comment by BrandonMathis** [comment]
Done

**Comment by dkniffin** [comment]
Closing this for now. I'm not sure how we're going to proceed with testing.

**Pull request closed without merging**
