### PR TITLE
Pull in latest roles

### PR DESCRIPTION
**Pull request by dkniffin**
### Why?

ANXS.postgresql got a version bump that I'd like to use

### What changed?

Bumped ANXS.postgresql to 1.8.0 and ran `ansible-galaxy install -r requirements.yml --force`

### CODE REVIEW

**Comment by prawl** [comment]
@BrandonMathis Can we get a review for this?

**Comment by dkniffin** [comment]
@prawl It looks like the tests are failing. If you want to look into it for me, you can. Otherwise, I'll try and get to it later today.

**Comment by prawl** [comment]
@dkniffin I'll look into it today.

**Comment by BrandonMathis** [comment]
This looks good. Thanks @dkniffin!

**Pull request merged**
