### PR TITLE
Fix an issue with monitrc

### PR DESCRIPTION
**Pull request by dkniffin**
After setting up a brand new box with tape, and trying to do `monit restart all`, I was running into this:

```
/etc/monitrc:290: Include failed -- Success '/etc/monit/conf-enabled/*'
```

To fix it, I simply commented out line 290 in `/etc/monitrc` (`include /etc/monit/conf-enabled/*`).

### CODE REVIEW

**Comment by dkniffin** [comment]
Brain dump:

I just paired with Brandon on this, and we realized it was a kind of different issue. Ultimately, we're pretty sure the issue was using the custom nginx role needed for letsencrypt. In order to resolve it, we decide it'd be best if that letsencrypt stuff lives inside tape. There's some more work to be done for that. Specifically, we'd like to remove all manual steps required (ie: right now you have to ssh into the server, and go through the blue screen flow). Trellis does something like that [here](https://github.com/roots/trellis/tree/master/roles/letsencrypt)

**Comment by dacur** [comment]
have you guys looked to see if a role already exists out there?  would this be helpful?  idk, i'll keep looking, too.

https://galaxy.ansible.com/jaywink/letsencrypt/

**Comment by dkniffin** [comment]
Just as an update here, I'm working on incorporating the role @dacur linked (jawink/letsencrypt), to do all the letsencrypt configuration. I'm having a little trouble getting it working, and I've opened an issue [here](https://github.com/jaywink/ansible-letsencrypt/issues/20). Once that's fixed, I should be really close to done with this.

As a side note, there is no good way to test the letsencrypt stuff. The way letsencrypt works (I think) is you configure your domain to point to your host, then letsencrypt talks to that domain, to make sure your box is actually that domain. Since we can't really set up a domain in docker/travis, it's not going to be possible to automate testing it. So instead, I'm manually deploying to a box, with this new role in place.

**Comment by BrandonMathis** [comment]
I'm kill this PR and pushing up a clean fix on a new branch.

**Pull request closed without merging**
