### PR TITLE
Notification if there are no changes on github

### PR DESCRIPTION
**Pull request by BrandonMathis**
## What Changed
* Notify user if there are no changes on github on deploy

### CODE REVIEW

**Comment by btushinde** [comment]
Implementation looks good to me. 

What does it output if there _are_ changes currently? Just the "changed" metadata for the given host?

**Comment by dkniffin** [comment]
Hmm. Not sure if we want it, but is there a way to stop the deployment? And then maybe a `--force` to do it anyway? Might be overkill.

**Comment by BrandonMathis** [comment]
I can add a `--force` flag in another feature @dkniffin :)

**Comment by dkniffin** [comment]
In that case, I think this looks good. :+1: To address Biko's comment, I assume it prints out nothing?

**Comment by BrandonMathis** [comment]
No, the debug print is pretty alarming. I promise

**Pull request merged**
